/*
 * This file was automatically generated by make-map from Mono.Fuse.dll.
 *
 * DO NOT MODIFY.
 */
#include <config.h>

#include <stdlib.h>
#include <string.h>
#include <mono/posix/limits.h>

#ifndef FUSE_USE_VERSION
#define FUSE_USE_VERSION 25
#endif /* ndef FUSE_USE_VERSION=25 */
#include <fuse.h>

#include "map.h"

int
Mono_Fuse_FromArgs (struct Mono_Fuse_Args *from, struct fuse_args *to)
{
	mph_return_val_if_overflow (int, from->argc, -1);
	mph_return_val_if_overflow (int, from->allocated, -1);

	memset (to, 0, sizeof(*to));

	to->argc      = from->argc;
	to->argv      = from->argv;
	to->allocated = from->allocated;

	return 0;
}


int
Mono_Fuse_ToArgs (struct fuse_args *from, struct Mono_Fuse_Args *to)
{
	mph_return_val_if_overflow (int, from->argc, -1);
	mph_return_val_if_overflow (int, from->allocated, -1);

	memset (to, 0, sizeof(*to));

	to->argc      = from->argc;
	to->argv      = from->argv;
	to->allocated = from->allocated;

	return 0;
}


